Feat/custom actions
AIforblog/aiblogfrontend pull request #98
Opened 2024-10-16 00:46 UTC by AdekolaToniloba

# **Description**
This pr implements the feature that allows the user to select the custom actions option when trying to create jobs.

###Figma
[Figma Link](https://www.figma.com/design/7DGLgn48eyVicv8JpkPchw/dRello?node-id=1138-10581&t=dmrDkU0guM2ok0on-1)

---

# **What were you told to do?**
Acceptance Criteria
- the description of each custom action should be displayed clearly and concisely , explaining what the user needs to do.
- clearly display the status of each custom action for the current user
- the styling of the custom actions section should align with the overall design of the platform

## **What did you do?**
- created the custom actions component
- integrated the component with the create- jobs form such that clicking the custom actions body will render the custom actions form.

### Route
**https://aiblogfe.vercel.app/create-job**
- Click next on the create jobs form until you get to the last step
- click on the custom actions button to render the custom actions form
- click on the button again to close the form.
# **Check List**

- [x] My code follows the code style of this project.
- [x] This PR does not contain plagiarized content.
- [x] The title and description of the PR are clear and explain the approach.
- [x] I am making a pull request against the **dev branch** (left side).
- [x] My commit message style matches our requested structure.
- [x] My code additions will not fail code linting checks or unit tests.
- [x] I am only making changes to files I was requested to.

---

# **Screenshots/Videos**

*Add relevant screenshots or videos here if applicable*
![screenbud-16edd274-0443-47ef-9bb4-60b72352273e](https://github.com/user-attachments/assets/02a5ac9e-de52-4974-85cf-b047b4c9aef4)
![screenbud-2dd7d7dd-20e3-4f90-8bb0-278dea1dcbe0](https://github.com/user-attachments/assets/91a846e7-e62d-493f-b943-fc3d1a5b34d8)
![screenbud-9e8f8cf3-8299-476e-9255-b0efbaa15738](https://github.com/user-attachments/assets/ac6d37bf-b383-4336-8d4f-8926e1d476fa)
![screenbud-2d18c46d-0fc4-45a1-8954-09690e19b3fd](https://github.com/user-attachments/assets/f3a1aa6a-98bc-4c15-b7f1-94bbf65336c6)
![screenbud-557fe64c-8ab4-473c-8ef8-b82af6d6455e](https://github.com/user-attachments/assets/74f869a6-325a-4088-b0dd-5ce11bfebf57)
![screenbud-eb992f77-5945-4114-9359-c2fc63173451](https://github.com/user-attachments/assets/20aef76c-21ce-413c-88b6-02f50e22f623)

---

2024-10-16 19:27 UTC, Maiqel1 requested changes
take out comments

2024-10-16 19:28 UTC, Maiqel1 commented on app/components/create-job/CustomActions.tsx
> +// import React, { useState } from "react";
...

2024-10-17 23:43 UTC, AdekolaToniloba commented on app/components/create-job/CustomActions.tsx
> +// import React, { useState } from "react";
Removed all the comments @Maiqel1

2024-10-18 19:42 UTC, Maiqel1 approved these changes

2024-10-18 19:42 UTC, merged